### PR TITLE
Matt tweaks2

### PR DESCRIPTION
**Pull request by mattsavarino**
WORK IN PROGRESS to see what it looks like deployed ;)

### CODE REVIEW

**Comment by mattsavarino** [comment]
I'm not able to fully test this locally so I'm attempting to deploy, but it fails w/ this error:

_The content server has rejected the request with: BadRequest
Reason: This static site already has the maximum number of environments (1). Please remove one and try again._

**Comment by dereklegenzoff** [comment]
@mattsavarino - sorry about that; I deleted the profile from my last PR and reran the pipeline. You should be all good to go now.

**Comment by dereklegenzoff** [comment]
@mattsavarino - let me know when this is ready to merge; all looks good to me

**Comment by dereklegenzoff** [comment]
@mattsavarino - looks like some of the logos aren't rendering properly; otherwise looks good to me

**Pull request merged**
